# MySQL (Customer Index)
infcommon_local_bote_mysql:
  image: mysql:5.5.45
  ports:
   - "3313:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root_pwd
   - MYSQL_DATABASE=felix
   - MYSQL_USER=infcommon
   - MYSQL_PASSWORD=infcommon_pwd
  volumes:
   - ./local_mysql_configuration:/docker-entrypoint-initdb.d:ro
   - /etc/localtime:/etc/localtime:ro

